[package]
name = "pglas"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg15"]
shared = []
pg11 = ["pgrx/pg11"]
pg12 = ["pgrx/pg12"]
pg13 = ["pgrx/pg13"]
pg14 = ["pgrx/pg14"]
pg15 = ["pgrx/pg15"]


[dependencies]
pgrx = "0.11.0"
lasrs = "0.1.3"
